### PR TITLE
Fix NPE

### PR DESCRIPTION
**Pull request by jruesga**
### java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
          at java.util.HashMap.<init>(HashMap.java:253)
          at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticateWithState(DigestAuthenticator.java:207)
          at com.burgstaller.okhttp.DispatchingAuthenticator.authenticateWithState(DispatchingAuthenticator.java:55)
          at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:40)

### CODE REVIEW

**Comment by rburgst** [comment]
Hi, how did you produce this NPE? IMHO if everything works correctly (i.e. the Interceptor always calling `authenticate` before `authenticateWithState`) this should never happen.
A test case would also be good.

**Comment by jruesga** [comment]
The stacktrace is this one https://paste.ruesga.com/view/2634bdfc

The problem is that DispatchingAuthenticator#authenticateWithState checks all available autenticators, but the order here matters, because it can call to DigestAuthenticator#authenticateWithState while the authentication happens with a BasicAuthenticator.

And this is the case of the stacktrace:

1.- At https://github.com/jruesga/rview/blob/master/gerrit/src/main/java/com/ruesga/rview/gerrit/GerritApiClient.java#L119, I created 2 authenticators (basic and digest), since Gerrit instances supports both scheme. Note the order here.
2.- For example https://review.lineageos.org, returns a Basic realm, and DispatchingAuthenticator#authenticate uses the BasicAuthenticator to perform the authentication challenge.
3.- After that a DispatchingAuthenticator#authenticateWithState happens, but this one walks for all available authenticators calling its authenticateWithState. In my case, digest is the first on the list, so a call to DigestAuthenticator#authenticateWithState happens without a DigestAuthenticator#authenticate.

**Comment by jruesga** [comment]
Upload a test case for check authenticator order effects (without d7f295a795660d99b3bd31fd4d90a46bdb18dfcc test #testCaching_withDigestAuthenticatorPreferredOrder will fail with a NPE)

**Comment by rburgst** [comment]
Thanks for the contribution, the thing with the ordering inside the hashmap is not important as long as the individual authenticators can cope with having an empty initial state.

**Pull request merged**
