### PR TITLE
Fix for #33

### LINKED ISSUE #33: DispatchingAuthenticator gets mixed up under high concurrency
When used in an application with many concurrent requests, I get the warning "previous digest authentication with same nonce failed, returning null" frequently right before I get a failed request.  I'm wondering if somehow the shared "parameters" object in DigestAuthenticator is getting overwritten by multiple concurrent requests and thus accidentally getting marked as stale.  I've been using DispatchingAuthenticator as directed in the README.md, but only using BasicAuthenticator or DigestAuthenticator because of #32.

### PR DESCRIPTION
**Pull request by sammefford**
This change fixes #33 by moving the shared parameters variable to a local variable.  Also adds a unit test to validate the fix by running the other digest unit tests in a multi-threaded env.

### CODE REVIEW

**Comment by rburgst** [comment]
Hey, thanks a lot for your contribution. I ran the code against a test server and it didnt authenticate. I need to analyze whats going wrong. However, from what I remember it was quite important that the parameters were cached between reused connection attempts.

**Comment by rburgst** [comment]
Its as I feared. Now when I do 2 requests after each other, there will be a 401 roundtrip for each request. 

```
--> GET /url1
<-- 401
--> GET /url1 (Digest)
<-- 200
--> GET /url2
<-- 401
--> GET /url2 (Digest2)
<-- 200
```

**Comment by sammefford** [comment]
Eek, that doesn't work.  I'm sure I can fix that.  Any chance you could add a unit test for that so we'll see it next time I make a change that does that?

**Comment by sammefford** [comment]
Did you figure out why the code didn't authenticate against a test server?

**Comment by rburgst** [comment]
Will do.

-- 
Rainer Burgstaller

**Comment by sammefford** [comment]
Did you figure out why the code didn't authenticate against a test server?

**Comment by rburgst** [comment]
classical PEBKAC, used a wrong password :(

**Pull request merged**
